# Generated by Django 2.1.7 on 2019-11-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trained', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
    ]
